## Numpy 모듈

In [1]:
import numpy as np

### 행렬의 덧셈

In [7]:
matrix1 = np.array([[2,7], [3,4], [6,1]])
matrix2 = np.array([[4,1], [2,6], [3,2]])

result = matrix1+ matrix2

print("덧셈 결과:\n", result)

덧셈 결과:
 [[ 6  8]
 [ 5 10]
 [ 9  3]]


### 행렬의 뺄셈

In [9]:
matrix1 = np.array([[2,7], [3,4], [6,1]])
matrix2 = np.array([[4,1], [2,6], [3,2]])

result = matrix1 - matrix2

print("뺄셈 결과:\n", result)

뺄셈 결과:
 [[-2  6]
 [ 1 -2]
 [ 3 -1]]


### 행렬의 스칼라 곱

In [10]:
matrix1 = np.array([[2,7], [3,4], [6,1]])
scalar1 = 2

result = scalar1 * matrix1

print("행렬의 스칼라 곱 결과:\n", result)

행렬의 스칼라 곱 결과:
 [[ 4 14]
 [ 6  8]
 [12  2]]


### 행렬의 원소 곱(matrix element multiplication)

행렬의 크기가 같아야 하며, 같은 위치의 원소들 끼리 곱한 행렬을 결과값으로 출력한다

표기는 $\odot$ 로 한다.<br>
ex) $$ A \odot B $$

In [11]:
matrix1 = np.array([[2,7], [3,4], [6,1]])
matrix2 = np.array([[4,1], [2,6], [3,2]])

result = np.multiply(matrix1, matrix2)

print("행렬의 원소 곱 결과:\n", result)

행렬의 원소 곱 결과:
 [[ 8  7]
 [ 6 24]
 [18  2]]


### 행렬 곱

행렬의 곱은 2가지 특이사항이 있다.

<ol>
    <li>2개의 행렬을 곱할 때는 크기를 확인해야 한다. <br>
    행렬A의 크기가 $m \times n $ 이고, 행렬 B의 크기가 $ a \times b $ 일 경우,
        $$ n = a \,과 \,같은 \,경우만 \,행렬 \,곱이 \,가능하다 $$
    </li>
    <li>행렬의 곱은 곱하는 순서에 따라서 결과가 다르다. <br>
       $$ AB \neq BA $$ 
    </li>
<ol>

In [15]:
#예제 1
matrix1 = np.array([[2,7], [3,4], [6,1]])
matrix2 = np.array([[3, -3, 5], [-1, 2, -1]])

result = np.matmul(matrix1, matrix2)

print("행렬 곱 결과:\n", result)

행렬 곱 결과:
 [[ -1   8   3]
 [  5  -1  11]
 [ 17 -16  29]]


In [16]:
#예제2
matrix1 = np.array([[2,7], [3,4]])
matrix2 = np.array([[3, -3], [-1, 2]])

result1 = np.matmul(matrix1, matrix2)
result2 = np.matmul(matrix2, matrix1)

print("행렬 곱 결과1:\n", result1)
print("행렬 곱 결과2:\n", result2)

행렬 곱 결과1:
 [[-1  8]
 [ 5 -1]]
행렬 곱 결과2:
 [[-3  9]
 [ 4  1]]


결과가 다르게 나오는 것을 확인할 수 있다.

In [10]:
import numpy as np

a = np.array([[], [-15,23]])
b = np.array([[1], [1]])
c = np.matmul(a,b)
c

array([[3],
       [8]])