# 행렬(matrix)

수나 식을 사각형 모양인 2차원 배열로 나타낸 것을 행렬이라고 한다. 행렬에서 가로줄을 행(raw), 세로줄을 열(column)이라고 한다.  
따라서 $mxn 행렬$을 m행 n열의 행렬 또는 m by n matrix라고 한다.

$$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$$
 
 넘파이에서 기본 행렬의 선언은 아래와 같다.  
 
 ## 행벡터(row vector) && 열벡터(column vector)

In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

row_vector = np.vstack((a,b,c))
column_vector = np.hstack((a.reshape(-1,1),b.reshape(-1,1),c.reshape(-1,1)))
print("행벡터 출력:")
print(row_vector)
print("열벡터 출력:")
print(column_vector)

행벡터 출력:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
열벡터 출력:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


열 벡터 같은 경우는 1차원인 벡터를 2차원인 수직으로 만들필요가 있다.  
reshape에서 -1은 "나머지 차원을 자동으로 계산"하라는 뜻이다.

# 정방행렬(square matrix)

정방 행렬은 행과 열의 개수가 같은 정사각형인 행렬을 뜻한다.

## 주대각 성분(main diagonal entry)

$$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$$
 
 <br>
 
 에서 행과 열의 번호가 같은 $a_{1,1},a_{2,2},a_{3,3}, .... , a_{m,n}$ 을 주대각 성분이라고 한다.  
 
 ## 대각 행렬(diagonal matrix)
 여기서 주대각 성분을 제외한 모든 성분이 0인 행렬을 __대각행렬__ 이라고 한다.
 $$diag(a_{1,1}, a_{2,2}, ... , a_{n,n}) =
 \begin{pmatrix}
  a_{1,1} & 0 & \cdots & 0 \\
  0 & a_{2,2} & \cdots & 0 \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  0 & 0 & \cdots & a_{m,n}
 \end{pmatrix}$$
 
 ## 단위 행렬(unit matrix)
 여기서 주대각 성분이 __1__ 이고 주대각 성분을 데외한 모든 성분이 0인 행렬을 __단위행렬__ 이라고 한다.
 $$I_{n} =
 \begin{pmatrix}
  1 & 0 & \cdots & 0 \\
  0 & 1 & \cdots & 0 \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  0 & 0 & \cdots & 1
 \end{pmatrix}$$
 <br>
 그리고 표현시 $n*n$행렬을 $I_{n}$으로도 표현한다.

### 대각행렬 만들기

주대각 성분이 1,2,3,4인 정방행렬을 만든다.

In [5]:
diag_element  = [1,2,3,4]
diag_matrix = np.diag(diag_element,k=0)
print(diag_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


k는 주대각 성분이 어디서부터 시작할지 정하는 역할이다.  

### 단위 행렬 만들기
$I_{4}$ 인 4*4 단위 행렬을 만든다.

In [6]:
unit_matrix = np.identity(4)
unit_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 행렬의 연산

## 행렬의 덧셈&뺄셈

행렬의 덧셈과 뺄셈은 서로 같은 크기의 행렬들만 가능하다.

In [8]:
matrix1 = np.array([[2,7], [3,4], [6,1]])
matrix2 = np.array([[4,1], [2,6], [3,2]])

result_add = matrix1+ matrix2
result_sub = matrix1 - matrix2

print("덧셈 결과:\n", result_add)
print("뺄셈 결과:\n", result_sub)

덧셈 결과:
 [[ 6  8]
 [ 5 10]
 [ 9  3]]
뺄셈 결과:
 [[-2  6]
 [ 1 -2]
 [ 3 -1]]


## 행렬의 스칼라 곱

행렬의 스칼라곱의 기본 성질로는 
1. $a(B + C) = aB + aC$
2. $(a + b)C = aC + bC$
3. $(ab)C = a(bC)$
4. $a(BC) = (aB)C = B(aC)$

In [9]:
matrix1 = np.array([[2,7], [3,4], [6,1]])
scalar1 = 2

result = scalar1 * matrix1

print("행렬의 스칼라 곱 결과:\n", result)

행렬의 스칼라 곱 결과:
 [[ 4 14]
 [ 6  8]
 [12  2]]


### 행렬 곱

행렬의 곱은 2가지 특이사항이 있다.

<ol>
    <li>2개의 행렬을 곱할 때는 크기를 확인해야 한다. <br>
    행렬A의 크기가 $m \times n $ 이고, 행렬 B의 크기가 $ a \times b $ 일 경우,
        $$ n = a \,과 \,같은 \,경우만 \,행렬 \,곱이 \,가능하다 $$
    </li>
    <li>행렬의 곱은 곱하는 순서에 따라서 결과가 다르다. <br>
       $$ AB \neq BA $$ 
    </li>
</ol>
<br>
따라서 행렬의 연산에 대한 기본 성질로는 아래와 같이 정의할 수 있다.<br>
1. $A + 0 = 0 + A = A$ (합에 대한 항등원의 영행렬)<br>
2. $IA = AI = A$ (곱에 대한 항등원인 단위행렬)<br>
3. $A + B = B + A$ (합에 대한 교환법칙)<br>
4. $(A + B) + C = A + (B + C)$ (합에 대한 결합법칙)<br>
5. $(AB)C = A(BC)$ (곱에 대한 결합법칙)<br>
6. $A(B + C) = AB + AC$ (분배법칙)<br>
7. $(A + B)C = AC + BC$ (분배법칙)<br>

In [10]:
#예제 1
matrix1 = np.array([[2,7], [3,4], [6,1]])
matrix2 = np.array([[3, -3, 5], [-1, 2, -1]])

result = np.matmul(matrix1, matrix2)

print("행렬 곱 결과:\n", result)

행렬 곱 결과:
 [[ -1   8   3]
 [  5  -1  11]
 [ 17 -16  29]]


In [11]:
#예제2
matrix1 = np.array([[2,7], [3,4]])
matrix2 = np.array([[3, -3], [-1, 2]])

result1 = np.matmul(matrix1, matrix2)
result2 = np.matmul(matrix2, matrix1)

print("행렬 곱 결과1:\n", result1)
print("행렬 곱 결과2:\n", result2)

행렬 곱 결과1:
 [[-1  8]
 [ 5 -1]]
행렬 곱 결과2:
 [[-3  9]
 [ 4  1]]


결과가 다르게 나오는 것을 확인할 수 있다.

## 행렬의 거듭제곱

행렬의 거듭제곱은 $n * n$행렬인 정방행렬에서만 가능하다.  
1. $A^0 = I$
2. $(A^b)^c = A^{bc}$
3. $A^bA^c = A^{b+c}$

In [13]:
matrix = np.array([[1,2],[4,5]])

power = np.linalg.matrix_power(matrix, 2)
print(power)

[[ 9 12]
 [24 33]]


## 행렬 곱의 소거법칙 적용 불가

행렬 $A, B, C$에 대해 $AB = AC$라고 해서 반드시 $B = C$는 아니다. 즉, 행렬 곱에서 소거법칙은 성립하지 않는다.

In [20]:
a = np.zeros((2,2))
b = np.array([[1,2],[3,4]])
c = np.array([[5,6],[7,8]])

ab = np.matmul(a, b)
ac = np.matmul(a, c)
print("AB 행렬: ")
print(ab)
print("AC 행렬: ")
print(ac)

AB 행렬: 
[[0. 0.]
 [0. 0.]]
AC 행렬: 
[[0. 0.]
 [0. 0.]]
